// svelte-app/src/Ticker.svelte
<style>
    /* nice background color */
    body {
        background-color:#f0f0f0;
    }
</style>

<script>
    import { onMount } from 'svelte';
	export let symbol;

	let coinmarketcapData = {};
	let price;

	onMount(async () => {
	    console.log("22AA"+coinmarketcapData);
        const res = await fetch('https://api.coinmarketcap.com/v1/ticker/?limit=10');
        let body = await res.json();

        coinmarketcapData = body.reduce(function(map, obj) {
            map[obj.symbol] = obj;
                return map;
            }, {});
        price = calcPrice();
    });

	function calcPrice() {
	    if (typeof coinmarketcapData[symbol] !== 'undefined') {
	        console.log(coinmarketcapData);
            return coinmarketcapData[symbol].name + " " + coinmarketcapData[symbol].price_usd;
        }
    }
</script>

<p>{price} USD</p>

// components/vue/ticker.vue
<template>
    <p>{{price}} USD</p>
</template>
<style>
    /* nice background color */
    body {
        background-color:#f0f0f0;
    }
</style>
<script>
    export default {
        props: ['symbol'],
        data: function () {
            return {
                coinmarketcapData: {}
            }
        },
        created: function () {
            fetch('https://api.coinmarketcap.com/v1/ticker/?limit=10')
                .then(response => response.json())
                .then(body => {
                    this.coinmarketcapData = body.reduce(function(map, obj) {
                        map[obj.symbol] = obj;
                        return map;
                    }, {});
                });
        },
        computed: {
            price: function() {
                if (typeof this.coinmarketcapData[this.symbol] !== 'undefined') {
                    return this.coinmarketcapData[this.symbol].name + " " + this.coinmarketcapData[this.symbol].price_usd;
                }
            }
        }
    }
</script>
